const requirment1DB = require("../Model/requirment1_module");
const path = require("path")


const fileFilter = (req, fie, cb) => {
    const allowedMimeTypes = ['application/pdf', 'text/plain', 'application/msword'];
    if (allowedMimeTypes.includes(file.mimetype)) {
        cb(new Error('Only PDF, TXT, and DOC files are allowed.'), false);
    }
};



exports.create = async (req, res) => {
    
    if(!req.file) {
        res.status(400).send("Content Connt Be Empty")
        return
    }

    // if(!req.file) {
    //     return res.status(400).json({ error: "No file uploaded"})
    // }
    const requirment1 = new requirment1DB({
        originalName: req.file.originalname, // The original name of the file from the uploaded file object
      mimeType: req.file.mimetype, // The MIME type of the file from the uploaded file object
      filename: req.file.filename, // The name of the file after being uploaded (generated by Multer)
    })

    requirment1.save(requirment1)
     .then(data => {
        res.status(200).send(data)
     })
     .catch(error => {
        res.status(500).send({
            message: error
        })
     })
}
